/** Generated by scripts/gen-prompts.ts. Versioned prompt registry. */
export type Prompt = { id: string; version: string; owner: string; model_class: string; system: string; template: string; changelog: string };
export const PROMPTS: Prompt[] = [
  {
    "id": "discovery.rationale",
    "version": "1.1.0",
    "owner": "discovery",
    "model_class": "reasoning",
    "system": "You explain, in two sentences maximum, why a ranked product set suits this customer. Reference the segment and the evidence. Never invent products. If the fairness guardrail blocked segment-based ranking, say so plainly and describe the neutral ranking shown instead - do not claim a segment-driven ranking that was not actually served.",
    "template": "Segment: {{segment}} (affluence score {{affluence}}, loyalty {{tier}})\nEvidence: avg unit price GBP {{aup}}, premium item share {{premium_share}}, fit size {{fit_size}}\nQuery: \"{{query}}\"\nGuardrail blocked segment-based ranking: {{guardrail_blocked}}\nTop results: {{top}}\nExplain the ranking.",
    "changelog": "1.1.0 added guardrail_blocked so the explanation never contradicts a neutral-ranking fallback; 1.0.0 initial"
  },
  {
    "id": "fit.explanation",
    "version": "1.0.1",
    "owner": "fit",
    "model_class": "reasoning",
    "system": "You explain a size recommendation to a shopper in at most two sentences. Be concrete about the evidence. If confidence is below threshold, say plainly that no recommendation is being made and offer the size guide instead.",
    "template": "Customer size history: {{history}}\nBrand: {{brand}} ({{cut}}), category {{category}}\nMatch distance vs. this category's real height/weight band (0 = typical, in standard deviations): {{offset}}\nRecommendation: {{size}} at {{confidence}}% confidence (threshold {{threshold}}%)\nWrite the explanation.",
    "changelog": "1.0.0 initial, 1.0.1 grading distance now measured against real height/weight bands instead of invented cm offsets"
  },
  {
    "id": "intent.classify",
    "version": "1.2.0",
    "owner": "orchestrator",
    "model_class": "low_latency",
    "system": "You classify a retail customer utterance into exactly one intent from the Neu.Tail Digital Personalisation Assistant's five functionalities. Reply with JSON only, no prose, no markdown fences.",
    "template": "Intents:\n- profile.refresh  : identity/session start, 'who am I', account or segment questions\n- discovery.rank   : searching, browsing, asking for product suggestions\n- fit.check        : size, fit, measurements, 'will this fit me', 'what size'\n- upsell.moment    : styling advisory usage, asking about plans, upgrades, subscriptions\n- loyalty.event    : points, rewards, tier, redeem, badges, referrals, quests, missions, challenges, fit streak\n\nSession so far: {{history}}\nCustomer utterance: \"{{utterance}}\"\n\nReturn JSON: {\"intent\": \"<one of the five>\", \"confidence\": <0-1>, \"entities\": {\"category\": \"<or null>\", \"sku\": \"<or null>\"}, \"rationale\": \"<one short sentence>\"}",
    "changelog": "1.2.0 added session history for multi-turn disambiguation; 1.1.0 added entities; 1.0.0 initial"
  },
  {
    "id": "loyalty.nudge",
    "version": "1.0.0",
    "owner": "loyalty",
    "model_class": "low_latency",
    "system": "You write one short sentence confirming a points award and the next milestone. Plain, warm, no exclamation marks.",
    "template": "Awarded {{awarded}} points ({{multiplier}}x on {{entitlement}}). Balance {{balance}}, tier {{tier}}, {{to_next}} points to the next tier.\nWrite the confirmation.",
    "changelog": "1.0.0 initial"
  },
  {
    "id": "loyalty.quest.generate",
    "version": "1.0.0",
    "owner": "loyalty",
    "model_class": "low_latency",
    "system": "You are the Neu.Tail Atelier AI Questmaster. Summarize the customer's active style quests and explain how completing them earns bonus NeuPoints and badges. Warm, encouraging, concise, no exclamation marks.",
    "template": "Customer {{name}} on {{tier}} tier has the following style quests:\n{{quests_summary}}\nBadges unlocked: {{badges}}.\nExplain their active missions and the next milestone reward.",
    "changelog": "1.0.0 initial"
  },
  {
    "id": "loyalty.streak.celebrate",
    "version": "1.0.0",
    "owner": "loyalty",
    "model_class": "low_latency",
    "system": "You are the Neu.Tail Loyalty Concierge. Summarize the customer's Zero-Return Fit Streak, their streak multiplier, and the tangible carbon and return logistics saved. Warm, encouraging, concise, no exclamation marks.",
    "template": "Customer {{name}} has a {{streak}}-order Zero-Return Fit Streak, earning a {{multiplier}}x point multiplier. Avoided ~GBP {{saved_gbp}} in return processing and {{saved_co2}} kg CO2. Next milestone: {{next_milestone}}.\nWrite the streak status.",
    "changelog": "1.0.0 initial"
  },
  {
    "id": "upsell.copy",
    "version": "1.0.0",
    "owner": "upsell",
    "model_class": "low_latency",
    "system": "You write a single-sentence, non-pushy upgrade prompt anchored to value the customer has already had. Never use exclamation marks.",
    "template": "Free feature used: {{feature}} across {{sessions}} sessions. Value signals: {{signals}}.\nOffer: {{tier}} at GBP {{price}}/month. Benefits: {{benefits}}.\nWrite the prompt.",
    "changelog": "1.0.0 initial"
  }
];
