/** Generated by scripts/gen-registry.ts. Seed set for the KV-backed registry. */
import type { ToolContract } from './types.js';
export const BUNDLED: ToolContract[] = [
  {
    "name": "analytics.returnrate.get",
    "version": "1.0.0",
    "purpose": "Return-rate baseline and reason-code decomposition across the seeded corpus.",
    "allowed_agents": [
      "orchestrator"
    ],
    "input_schema": {},
    "output_schema": {
      "return_rate": "number",
      "reason_mix": "object"
    },
    "transport": {
      "service": "services",
      "method": "GET",
      "path": "/analytics/return-rate"
    }
  },
  {
    "name": "catalogue.inventory.get",
    "version": "1.0.0",
    "purpose": "Live stock by size for one SKU.",
    "allowed_agents": [
      "discovery",
      "fit"
    ],
    "input_schema": {
      "sku": {
        "type": "string",
        "required": true
      }
    },
    "output_schema": {
      "sku": "string",
      "sizes": "array"
    },
    "transport": {
      "service": "services",
      "method": "GET",
      "path": "/inventory/{sku}"
    }
  },
  {
    "name": "catalogue.product.get",
    "version": "1.0.0",
    "purpose": "Fetch a single product record by SKU.",
    "allowed_agents": [
      "discovery",
      "fit"
    ],
    "input_schema": {
      "sku": {
        "type": "string",
        "required": true
      }
    },
    "output_schema": {
      "sku": "string",
      "title": "string",
      "price_gbp": "number",
      "cut": "string",
      "image_url": "string"
    },
    "transport": {
      "service": "services",
      "method": "GET",
      "path": "/catalogue/{sku}"
    }
  },
  {
    "name": "catalogue.search",
    "version": "1.0.0",
    "purpose": "Search the product catalogue. Returns unranked candidates with price tier, stock and cut.",
    "allowed_agents": [
      "discovery"
    ],
    "input_schema": {
      "q": {
        "type": "string",
        "required": true
      },
      "category": {
        "type": "string",
        "required": false
      },
      "department": {
        "type": "string",
        "required": false,
        "description": "'women' | 'men' | 'unisex' - hard-filters out the opposite department, unisex products always included"
      },
      "limit": {
        "type": "integer",
        "required": false,
        "default": 40
      },
      "searchMode": {
        "type": "string",
        "required": false,
        "default": "lexical",
        "description": "\"lexical\" (default) or \"semantic\" - embedding-based retrieval via Workers AI + Vectorize."
      }
    },
    "output_schema": {
      "query": "string",
      "candidates": "integer",
      "results": "array"
    },
    "transport": {
      "service": "services",
      "method": "GET",
      "path": "/catalogue/search"
    }
  },
  {
    "name": "context.read",
    "version": "1.0.0",
    "purpose": "Read the customer's long-term (cross-session) agent memory.",
    "allowed_agents": [
      "profiling",
      "discovery",
      "fit",
      "upsell",
      "loyalty",
      "orchestrator"
    ],
    "input_schema": {
      "customer_id": {
        "type": "string",
        "required": true
      }
    },
    "output_schema": {
      "context": "object"
    },
    "transport": {
      "service": "services",
      "method": "GET",
      "path": "/context/{customer_id}"
    }
  },
  {
    "name": "context.write",
    "version": "1.0.0",
    "purpose": "Write a key into long-term agent memory, visible to every agent in later sessions.",
    "allowed_agents": [
      "profiling",
      "discovery",
      "fit",
      "upsell",
      "loyalty"
    ],
    "input_schema": {
      "customer_id": {
        "type": "string",
        "required": true
      },
      "key": {
        "type": "string",
        "required": true
      },
      "value": {
        "type": "object",
        "required": true
      }
    },
    "output_schema": {
      "written": "boolean"
    },
    "transport": {
      "service": "services",
      "method": "POST",
      "path": "/context/{customer_id}"
    }
  },
  {
    "name": "customer.events.get",
    "version": "1.0.0",
    "purpose": "Read recent behavioural / clickstream events for a customer.",
    "allowed_agents": [
      "profiling",
      "discovery"
    ],
    "input_schema": {
      "customer_id": {
        "type": "string",
        "required": true
      },
      "limit": {
        "type": "integer",
        "required": false,
        "default": 40
      }
    },
    "output_schema": {
      "events": "array"
    },
    "transport": {
      "service": "services",
      "method": "GET",
      "path": "/customers/{customer_id}/events"
    }
  },
  {
    "name": "customer.profile.get",
    "version": "1.0.0",
    "purpose": "Load the enriched Customer 360 profile: identity, loyalty, transaction and returns history.",
    "allowed_agents": [
      "profiling"
    ],
    "input_schema": {
      "customer_id": {
        "type": "string",
        "required": true,
        "description": "Customer identifier"
      }
    },
    "output_schema": {
      "identity": "object",
      "loyalty": "object",
      "transactions": "object",
      "returns": "object",
      "consent": "object"
    },
    "transport": {
      "service": "services",
      "method": "GET",
      "path": "/customers/{customer_id}/profile"
    }
  },
  {
    "name": "customer.returns.get",
    "version": "1.0.0",
    "purpose": "Read a customer's returns history with reason codes.",
    "allowed_agents": [
      "profiling",
      "fit"
    ],
    "input_schema": {
      "customer_id": {
        "type": "string",
        "required": true
      }
    },
    "output_schema": {
      "returns": "array"
    },
    "transport": {
      "service": "services",
      "method": "GET",
      "path": "/customers/{customer_id}/returns"
    }
  },
  {
    "name": "fit.observation.record",
    "version": "1.0.0",
    "purpose": "Write a confirmed fit observation back to the fit store.",
    "allowed_agents": [
      "fit"
    ],
    "input_schema": {
      "customer_id": {
        "type": "string",
        "required": true
      },
      "category": {
        "type": "string",
        "required": true
      },
      "preferred_size": {
        "type": "string",
        "required": true
      },
      "fit_preference": {
        "type": "string",
        "required": false
      }
    },
    "output_schema": {
      "recorded": "boolean"
    },
    "transport": {
      "service": "services",
      "method": "POST",
      "path": "/fit/{customer_id}/observation"
    }
  },
  {
    "name": "fit.profile.get",
    "version": "1.0.0",
    "purpose": "Read the customer's fit profile, consent flag and fit-related return history.",
    "allowed_agents": [
      "fit",
      "discovery"
    ],
    "input_schema": {
      "customer_id": {
        "type": "string",
        "required": true
      }
    },
    "output_schema": {
      "consent_fit": "boolean",
      "measurements": "object",
      "profiles": "array",
      "fit_returns": "array"
    },
    "transport": {
      "service": "services",
      "method": "GET",
      "path": "/fit/{customer_id}"
    }
  },
  {
    "name": "fit.sizechart.get",
    "version": "1.0.0",
    "purpose": "Real per-category weight/height size bands, derived from a ~120k-row anthropometric dataset. Brand nuance is applied separately via the product's own cut.",
    "allowed_agents": [
      "fit"
    ],
    "input_schema": {
      "category": {
        "type": "string",
        "required": true
      }
    },
    "output_schema": {
      "category": "string",
      "grading": "array"
    },
    "transport": {
      "service": "services",
      "method": "GET",
      "path": "/size-charts/{category}"
    }
  },
  {
    "name": "loyalty.account.get",
    "version": "1.0.0",
    "purpose": "Read points balance, tier and engagement score.",
    "allowed_agents": [
      "loyalty",
      "upsell"
    ],
    "input_schema": {
      "customer_id": {
        "type": "string",
        "required": true
      }
    },
    "output_schema": {
      "tier": "string",
      "points_balance": "integer"
    },
    "transport": {
      "service": "services",
      "method": "GET",
      "path": "/loyalty/{customer_id}"
    }
  },
  {
    "name": "loyalty.accrue",
    "version": "1.0.0",
    "purpose": "Award points for an action, applying the entitlement multiplier.",
    "allowed_agents": [
      "loyalty"
    ],
    "input_schema": {
      "customer_id": {
        "type": "string",
        "required": true
      },
      "base_points": {
        "type": "integer",
        "required": true
      },
      "multiplier": {
        "type": "number",
        "required": false,
        "default": 1
      },
      "reason": {
        "type": "string",
        "required": false
      }
    },
    "output_schema": {
      "awarded": "integer",
      "balance": "integer",
      "tier": "string",
      "liability_gbp": "number"
    },
    "transport": {
      "service": "services",
      "method": "POST",
      "path": "/loyalty/{customer_id}/accrue"
    }
  },
  {
    "name": "loyalty.redeem",
    "version": "1.0.0",
    "purpose": "Redeem points against a reward and release the point liability.",
    "allowed_agents": [
      "loyalty"
    ],
    "input_schema": {
      "customer_id": {
        "type": "string",
        "required": true
      },
      "points": {
        "type": "integer",
        "required": true
      }
    },
    "output_schema": {
      "redeemed": "boolean",
      "balance": "integer"
    },
    "transport": {
      "service": "services",
      "method": "POST",
      "path": "/loyalty/{customer_id}/redeem"
    }
  },
  {
    "name": "subscription.get",
    "version": "1.0.0",
    "purpose": "Read current subscription tier and price.",
    "allowed_agents": [
      "upsell",
      "loyalty"
    ],
    "input_schema": {
      "customer_id": {
        "type": "string",
        "required": true
      }
    },
    "output_schema": {
      "tier": "string",
      "price_gbp_month": "number"
    },
    "transport": {
      "service": "services",
      "method": "GET",
      "path": "/subscriptions/{customer_id}"
    }
  },
  {
    "name": "subscription.upgrade",
    "version": "1.0.0",
    "purpose": "Create or change a subscription and apply the entitlement.",
    "allowed_agents": [
      "upsell"
    ],
    "input_schema": {
      "customer_id": {
        "type": "string",
        "required": true
      },
      "tier": {
        "type": "string",
        "required": true
      }
    },
    "output_schema": {
      "tier": "string",
      "entitlement_active": "boolean"
    },
    "transport": {
      "service": "services",
      "method": "POST",
      "path": "/subscriptions/{customer_id}"
    }
  },
  {
    "name": "usage.get",
    "version": "1.0.0",
    "purpose": "Read free-tier feature usage, entitlement state and offer history.",
    "allowed_agents": [
      "upsell"
    ],
    "input_schema": {
      "customer_id": {
        "type": "string",
        "required": true
      },
      "feature": {
        "type": "string",
        "required": false
      }
    },
    "output_schema": {
      "entitlement": "string",
      "sessions": "integer",
      "value_signals": "array",
      "last_offer_at": "string"
    },
    "transport": {
      "service": "services",
      "method": "GET",
      "path": "/usage/{customer_id}"
    }
  },
  {
    "name": "usage.offer.record",
    "version": "1.0.0",
    "purpose": "Record that an upgrade offer was shown, for frequency-cap accounting.",
    "allowed_agents": [
      "upsell"
    ],
    "input_schema": {
      "customer_id": {
        "type": "string",
        "required": true
      }
    },
    "output_schema": {
      "recorded": "boolean"
    },
    "transport": {
      "service": "services",
      "method": "POST",
      "path": "/usage/{customer_id}/offer-shown"
    }
  }
];
