/** Bundles prompts/*.json into a TS module for the LLM gateway Worker. */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const __dirname = dirname(fileURLToPath(import.meta.url));
const dir = resolve(__dirname, '../packages/llm/prompts');
const prompts = readdirSync(dir).filter(f => f.endsWith('.json'))
  .map(f => JSON.parse(readFileSync(resolve(dir, f), 'utf8')));
writeFileSync(resolve(__dirname, '../packages/llm/src/prompts.ts'),
  `/** Generated by scripts/gen-prompts.ts. Versioned prompt registry. */\n` +
  `export type Prompt = { id: string; version: string; owner: string; model_class: string; system: string; template: string; changelog: string };\n` +
  `export const PROMPTS: Prompt[] = ${JSON.stringify(prompts, null, 2)};\n`);
console.log(`bundled ${prompts.length} prompts`);
