/** Bundles registry/tools/*.json into a TS module so the Worker ships with its contracts. */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const __dirname = dirname(fileURLToPath(import.meta.url));
const dir = resolve(__dirname, '../packages/tools/registry/tools');
const contracts = readdirSync(dir).filter(f => f.endsWith('.json'))
  .map(f => JSON.parse(readFileSync(resolve(dir, f), 'utf8')));
writeFileSync(resolve(__dirname, '../packages/tools/src/bundled.ts'),
  `/** Generated by scripts/gen-registry.ts. Seed set for the KV-backed registry. */\n` +
  `import type { ToolContract } from './types.js';\n` +
  `export const BUNDLED: ToolContract[] = ${JSON.stringify(contracts, null, 2)};\n`);
console.log(`bundled ${contracts.length} contracts`);
