/**
 * Seed generator for D1.
 *
 * Emits packages/services/seed.sql as batched multi-row INSERTs, so `wrangler d1 execute`
 * can load it locally or remotely. Same deterministic PRNG and the same exact-quota
 * returns logic as the original build: 34.0% return rate, 58/22/12/8 reason split.
 */
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, '../packages/services/seed.sql');

let _s = 20260913 >>> 0;
const rnd = () => {
  _s = (_s + 0x6D2B79F5) >>> 0;
  let t = _s;
  t = Math.imul(t ^ (t >>> 15), t | 1);
  t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};
const pick = <T,>(a: readonly T[]): T => a[Math.floor(rnd() * a.length) % a.length];
const int = (lo: number, hi: number) => lo + Math.floor(rnd() * (hi - lo + 1));
const r2 = (n: number) => Math.round(n * 100) / 100;
const q = (v: unknown) => v === null || v === undefined ? 'NULL'
  : typeof v === 'number' ? String(v)
  : `'${String(v).replace(/'/g, "''")}'`;

const CATEGORIES = ['dresses','tops','knitwear','outerwear','trousers','skirts','footwear','accessories'] as const;
const SIZES = ['XS','S','M','L','XL'] as const;
const BRANDS = [
  { name:'Aurelia', tier:'premium' }, { name:'Verano', tier:'premium' },
  { name:'Halston Row', tier:'core' }, { name:'Bexley', tier:'core' },
  { name:'Neu Basics', tier:'private_label' }, { name:'Neu Everyday', tier:'value' },
  { name:'Kestrel', tier:'value' },
] as const;
const SINGULAR: Record<string,string> = { dresses:'dress', tops:'top', knitwear:'knit', outerwear:'coat',
  trousers:'trousers', skirts:'skirt', footwear:'shoes', accessories:'accessory' };
const COLOURS = ['midnight','ivory','sage','rust','charcoal','plum','camel','olive'];
const MATERIALS = ['silk blend','organic cotton','merino wool','linen','viscose','recycled poly','cashmere blend'];
const STYLES = ['occasion','workwear','everyday','party','minimal','statement','layering','holiday'];
const CUTS = ['runs_small','true_to_size','runs_large'] as const;
const CHANNELS = ['web','app','store'];
const PRICE_BANDS: Record<string,[number,number]> = { premium:[110,480], core:[45,130], private_label:[18,55], value:[9,38] };
const REASON_MIX: Array<[string, number]> = [['size_fit',0.58],['changed_mind',0.22],['quality_defect',0.12],['other',0.08]];
const FIT_DETAIL = ['too small on the bust','too tight on the waist','length too long','shoulders too narrow','too large overall'];
const BASE = { XS:82, S:87, M:92, L:98, XL:105 } as const;
const TARGET = 0.34, MONTHS = 12;

const now = new Date('2026-09-13T09:00:00Z');
const daysAgo = (d: number) => new Date(now.getTime() - d * 864e5).toISOString();

const sql: string[] = ['-- Generated by scripts/gen-seed.ts. Do not edit by hand.', 'PRAGMA defer_foreign_keys = true;'];
/** D1 caps statement size, so rows go out in batches of 80. */
function emit(table: string, cols: string[], rows: unknown[][]) {
  for (let i = 0; i < rows.length; i += 80) {
    const chunk = rows.slice(i, i + 80);
    sql.push(`INSERT INTO ${table} (${cols.join(',')}) VALUES\n` +
      chunk.map(r => `(${r.map(q).join(',')})`).join(',\n') + ';');
  }
}

// ---- products + inventory + charts
type P = { sku:string; category:string; brand:string; price:number; tier:string; cut:string };
const products: P[] = [];
const pRows: unknown[][] = [], invRows: unknown[][] = [];
for (let i = 1; i <= 1200; i++) {
  const brand = pick(BRANDS), category = pick(CATEGORIES);
  const [lo, hi] = PRICE_BANDS[brand.tier];
  const price = r2(lo + rnd() * (hi - lo));
  const colour = pick(COLOURS), cut = pick(CUTS);
  const styles = [pick(STYLES), pick(STYLES)].filter((v, idx, a) => a.indexOf(v) === idx);
  const sku = `SKU-${String(i).padStart(5,'0')}`;
  const baseReturn = brand.tier === 'premium' ? 0.22 : brand.tier === 'value' ? 0.41 : 0.32;
  const returnRate = r2(Math.min(0.62, baseReturn + (cut === 'true_to_size' ? -0.06 : 0.05) + rnd() * 0.06));
  pRows.push([sku, `${brand.name} ${colour} ${SINGULAR[category]}`, category, brand.name, price,
    brand.tier, colour, pick(MATERIALS), styles.join(','), cut, r2(3.2 + rnd() * 1.7), returnRate]);
  for (const s of SIZES) invRows.push([sku, s, int(0, 40)]);
  products.push({ sku, category, brand: brand.name, price, tier: brand.tier, cut });
}
emit('products', ['sku','title','category','brand','price_gbp','price_tier','colour','material','style_tags','cut','rating','return_rate'], pRows);
emit('inventory', ['sku','size','qty'], invRows);

const chartRows: unknown[][] = [];
for (const b of BRANDS) for (const cat of CATEGORIES) for (const s of SIZES) {
  const off = b.tier === 'premium' ? -2.5 : b.tier === 'value' ? 2.5 : 0;
  chartRows.push([b.name, cat, s, BASE[s] + off, BASE[s] - 18 + off, BASE[s] + 6 + off, 2.0]);
}
emit('size_charts', ['brand','category','size','bust_cm','waist_cm','hip_cm','grading_tolerance_cm'], chartRows);

// ---- customers
type Cust = { id:string; affluence:string; orders:number; tenure:number; fit:string; consentFit:number };
const PERSONAS = [
  { id:'C001', name:'Priya Raman', email:'priya.raman@example.com', city:'London', affluence:'affluent',
    tenure:38, orders:24, fit:'rich', consentFit:1, sub:'plus', styling:9,
    note:'AFFLUENT + LOYAL + rich fit history. Premium ranking, high-confidence fit call.' },
  { id:'C002', name:'Aditi Sharma', email:'aditi.sharma@example.com', city:'Leeds', affluence:'value_seeking',
    tenure:2, orders:2, fit:'none', consentFit:0, sub:'free', styling:0,
    note:'LESS AFFLUENT + NEW + no fit history and no consent. Value ranking, fit agent abstains.' },
  { id:'C003', name:'Meera Iyer', email:'meera.iyer@example.com', city:'Manchester', affluence:'mid',
    tenure:14, orders:9, fit:'rich', consentFit:1, sub:'free', styling:3,
    note:'UPSELL TRIGGER. Third free Styling Advisory session -> Plus offer -> 2x loyalty accrual.' },
  // Appended last, not inserted earlier: its declared* fields below are fixed literals
  // rather than spendFor/aupFor/premFor, and every count here is 0, so it draws zero
  // extra numbers from the shared PRNG - C001/C002/C003's own generated data (and every
  // number quoted about them in README.md/DEMO.md) is unaffected by this entry existing.
  { id:'C000', name:'Guest Visitor', email:'guest@example.com', city:'London', affluence:'value_seeking',
    tenure:0, orders:0, fit:'none', consentFit:0, sub:'free', styling:0,
    declaredSpend:180, declaredAup:22, declaredPremium:0.04,
    note:'GUEST. No order or fit history - a brand-new anonymous visitor. Thin-history ranking, fit agent abstains, no subscription/loyalty offer until signed in.' },
];
const NAMES = ['Nisha Kapoor','Tom Whitfield','Grace Okoro','Dan Lawson','Aiko Tanaka','Ravi Menon','Sofia Duarte',
 'Callum Reid','Elena Petrova','Marcus Bell','Hana Yilmaz','Jonah Price','Leila Haddad','Owen Shaw','Freya Lindqvist',
 'Amara Diallo','Ben Costa','Ingrid Moss','Sanjay Pillai','Clara Ferreira','Noor Rahman','Ethan Crowe','Mei Lin',
 'Patrick Doyle','Zara Ahmed','Luca Romano','Bethany Hart','Kofi Mensah','Rosa Vega','Simon Aldridge','Tanvi Desai',
 'Rachel Byrne','Idris Olawale','Katya Sokolova','Will Hargreaves','Priti Nair','Andre Baptiste'];
const CITIES = ['London','Manchester','Birmingham','Bristol','Leeds','Glasgow','Cardiff','Edinburgh','Nottingham','Brighton'];

const tierFor = (lt:number) => lt > 9000 ? 'Platinum' : lt > 4500 ? 'Gold' : lt > 1500 ? 'Silver' : 'Bronze';
const spendFor = (a:string) => a === 'affluent' ? int(2400,5200) : a === 'mid' ? int(700,2000) : int(120,600);
const aupFor = (a:string) => a === 'affluent' ? r2(95 + rnd()*90) : a === 'mid' ? r2(42 + rnd()*35) : r2(14 + rnd()*22);
const premFor = (a:string) => a === 'affluent' ? r2(0.55 + rnd()*0.3) : a === 'mid' ? r2(0.18 + rnd()*0.2) : r2(0.02 + rnd()*0.1);

const customers: Cust[] = [];
const cRows: unknown[][] = [], lRows: unknown[][] = [], sRows: unknown[][] = [];
for (const p of PERSONAS) {
  const lifetime = p.affluence === 'affluent' ? 6400 : p.affluence === 'mid' ? 2100 : 210;
  cRows.push([p.id, p.name, p.email, p.city, daysAgo(p.tenure*30),
    p.declaredSpend ?? spendFor(p.affluence),
    p.declaredAup ?? aupFor(p.affluence),
    p.declaredPremium ?? premFor(p.affluence), p.consentFit, 1, p.note]);
  lRows.push([p.id, tierFor(lifetime), Math.round(lifetime*0.35), lifetime,
    p.affluence === 'affluent' ? 0.84 : p.affluence === 'mid' ? 0.58 : 0.21,
    lifetime > 4500 ? 9000 - lifetime : 4500 - lifetime]);
  sRows.push([p.id, p.sub, p.sub === 'plus' ? 4.99 : p.sub === 'premium' ? 9.99 : 0,
    p.sub === 'free' ? null : daysAgo(120), null, 0]);
  customers.push({ id: p.id, affluence: p.affluence, orders: p.orders, tenure: p.tenure, fit: p.fit, consentFit: p.consentFit });
}
NAMES.forEach((name, i) => {
  const id = `C${String(i+4).padStart(3,'0')}`;
  const affluence = i % 3 === 0 ? 'affluent' : i % 3 === 1 ? 'mid' : 'value_seeking';
  const tenure = int(1,48), orders = tenure < 4 ? int(1,3) : int(4,26);
  const lifetime = affluence === 'affluent' ? int(4000,12000) : affluence === 'mid' ? int(1200,4400) : int(80,1400);
  const consentFit = rnd() > 0.3 ? 1 : 0;
  cRows.push([id, name, `${name.toLowerCase().replace(/[^a-z]+/g,'.')}@example.com`, pick(CITIES),
    daysAgo(tenure*30), spendFor(affluence), aupFor(affluence), premFor(affluence), consentFit, rnd() > 0.2 ? 1 : 0, null]);
  lRows.push([id, tierFor(lifetime), Math.round(lifetime*0.3), lifetime, r2(rnd()),
    lifetime > 4500 ? Math.max(0, 9000-lifetime) : Math.max(0, 4500-lifetime)]);
  const sub = rnd() > 0.88 ? 'plus' : 'free';
  sRows.push([id, sub, sub === 'plus' ? 4.99 : 0, sub === 'free' ? null : daysAgo(int(30,300)), null, int(0,2)]);
  customers.push({ id, affluence, orders, tenure, fit: orders > 6 && consentFit ? 'rich' : orders > 2 ? 'thin' : 'none', consentFit });
});
emit('customers', ['id','name','email','city','joined_at','annual_spend_gbp','avg_unit_price_gbp','premium_share','consent_fit','consent_marketing','seed_persona'], cRows);
emit('loyalty_accounts', ['customer_id','tier','points_balance','lifetime_points','engagement_score','points_to_next_tier'], lRows);
emit('subscriptions', ['customer_id','tier','price_gbp_month','started_at','last_offer_at','offers_declined'], sRows);

// ---- orders, items, returns
const premiumPool = products.filter(p => ['premium','core'].includes(p.tier));
const valuePool = products.filter(p => ['value','private_label','core'].includes(p.tier));
type Line = { itemId:string; customerId:string; orderId:string; sku:string; size:string; category:string };
const lines: Line[] = [];
const oRows: unknown[][] = [], iRows: unknown[][] = [];
for (const c of customers) {
  const pool = c.affluence === 'affluent' ? premiumPool : c.affluence === 'mid' ? products : valuePool;
  const window = Math.min(MONTHS*30, c.tenure*30);
  for (let o = 0; o < c.orders; o++) {
    const orderId = `ORD-${c.id}-${String(o+1).padStart(3,'0')}`;
    const n = int(1,3);
    let total = 0;
    for (let li = 0; li < n; li++) {
      const p = pick(pool), size = pick(SIZES), itemId = `${orderId}-L${li+1}`;
      iRows.push([itemId, orderId, c.id, p.sku, size, 1, p.price]);
      total += p.price;
      lines.push({ itemId, customerId: c.id, orderId, sku: p.sku, size, category: p.category });
    }
    oRows.push([orderId, c.id, daysAgo(int(1, Math.max(2, window))), pick(CHANNELS), r2(total)]);
  }
}
emit('orders', ['id','customer_id','placed_at','channel','total_gbp'], oRows);
emit('order_items', ['id','order_id','customer_id','sku','size','qty','price_gbp'], iRows);

const target = Math.round(lines.length * TARGET);
const shuffled = [...lines];
for (let i = shuffled.length - 1; i > 0; i--) { const j = Math.floor(rnd()*(i+1)); [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]; }
const returnedSet = new Set(shuffled.slice(0, target).map(l => l.itemId));
const queue: string[] = [];
let assigned = 0;
REASON_MIX.forEach(([code, w], i) => {
  const n = i === REASON_MIX.length - 1 ? target - assigned : Math.round(target * w);
  assigned += n;
  for (let k = 0; k < n; k++) queue.push(code);
});

const rRows: unknown[][] = [];
const fitObs = new Map<string, { category:string; size:string; kept:boolean }[]>();
let qi = 0;
for (const l of lines) {
  const kept = !returnedSet.has(l.itemId);
  if (!fitObs.has(l.customerId)) fitObs.set(l.customerId, []);
  fitObs.get(l.customerId)!.push({ category: l.category, size: l.size, kept });
  if (kept) continue;
  const reason = queue[qi++];
  rRows.push([`RET-${l.itemId}`, l.itemId, l.orderId, l.customerId, l.sku, l.size,
    daysAgo(int(1,20)), reason, reason === 'size_fit' ? pick(FIT_DETAIL) : null]);
}
emit('returns', ['id','order_item_id','order_id','customer_id','sku','size','returned_at','reason_code','reason_detail'], rRows);

// ---- fit profiles
const fRows: unknown[][] = [];
for (const c of customers) {
  if (c.fit === 'none' || !c.consentFit || c.id === 'C001' || c.id === 'C003') continue;
  const byCat = new Map<string, Record<string, number>>();
  for (const o of (fitObs.get(c.id) ?? []).filter(o => o.kept)) {
    if (!byCat.has(o.category)) byCat.set(o.category, {});
    const m = byCat.get(o.category)!; m[o.size] = (m[o.size] ?? 0) + 1;
  }
  for (const [category, sizes] of byCat) {
    const [size, count] = Object.entries(sizes).sort((a,b) => b[1]-a[1])[0] ?? [];
    if (!size) continue;
    if (c.fit === 'thin' && count < 2) continue;
    const base = BASE[size as keyof typeof BASE];
    fRows.push([c.id, category, size, rnd() > 0.7 ? 'relaxed' : 'regular',
      base + r2(rnd()*2-1), base - 18 + r2(rnd()*2-1), base + 6 + r2(rnd()*2-1), count, daysAgo(int(3,60))]);
  }
}
// Demo personas get guaranteed, hand-set fit history in the demo category.
fRows.push(['C001','dresses','M','regular',91.5,73.0,97.5,7,daysAgo(11)]);
fRows.push(['C003','dresses','S','relaxed',86.0,68.5,92.0,4,daysAgo(23)]);
emit('fit_profiles', ['customer_id','category','preferred_size','fit_preference','bust_cm','waist_cm','hip_cm','observations','updated_at'], fRows);

// ---- events + feature usage
const EVENT_TYPES = ['session.start','search.query','pdp.view','basket.add','wishlist.add','loyalty.view'];
const QUERIES = ['occasion dress','winter coat','work trousers','knit jumper','party dress','linen shirt'];
const eRows: unknown[][] = [];
let ev = 0;
for (const c of customers) {
  const n = c.affluence === 'affluent' ? int(60,140) : c.affluence === 'mid' ? int(25,70) : int(6,30);
  for (let i = 0; i < n; i++) {
    const type = pick(EVENT_TYPES), p = pick(products);
    eRows.push([`EV-${++ev}`, c.id, daysAgo(int(1,300)), type,
      JSON.stringify(type === 'search.query' ? { q: pick(QUERIES) } : { sku: p.sku, category: p.category, price_tier: p.tier })]);
  }
}
emit('events', ['id','customer_id','occurred_at','type','payload'], eRows);

const uRows: unknown[][] = [];
for (const p of PERSONAS) {
  for (let i = 0; i < p.styling; i++) {
    uRows.push([`FU-${p.id}-${i+1}`, p.id, 'styling_advisory', `S-${p.id}-${i+1}`,
      daysAgo(p.id === 'C003' ? ([9,5,1][i] ?? int(1,30)) : int(1,90)),
      i % 2 === 0 ? 'saved_look' : 'shared_board']);
  }
}
emit('feature_usage', ['id','customer_id','feature','session_id','used_at','value_signal'], uRows);

writeFileSync(OUT, sql.join('\n') + '\n');

const byReason = rRows.reduce<Record<string, number>>((m, r) => ({ ...m, [r[7] as string]: (m[r[7] as string] ?? 0) + 1 }), {});
console.log('\n  seed.sql written\n  ' + '-'.repeat(50));
console.log(`  customers            ${cRows.length}`);
console.log(`  products             ${pRows.length}`);
console.log(`  order items          ${iRows.length}`);
console.log(`  returns              ${rRows.length}`);
console.log(`  RETURN RATE          ${(rRows.length/iRows.length*100).toFixed(1)}%   (baseline target 34%)`);
for (const [k,v] of Object.entries(byReason).sort((a,b)=>b[1]-a[1])) {
  console.log(`    ${k.padEnd(16)} ${(v/rRows.length*100).toFixed(1)}%`);
}
console.log(`  statements           ${sql.length}`);
console.log('');
